#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v18
# autospec commit: f35655a
#
Name     : tree-sitter
Version  : 0.23.0
Release  : 8
URL      : https://github.com/tree-sitter/tree-sitter/archive/v0.23.0/tree-sitter-0.23.0.tar.gz
Source0  : https://github.com/tree-sitter/tree-sitter/archive/v0.23.0/tree-sitter-0.23.0.tar.gz
Source1  : http://localhost/cgit/vendor/tree-sitter/snapshot/tree-sitter-2024-08-26-17-00-12.tar.xz
Summary  : An incremental parsing system for programming tools
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 GPL-2.0 HPND ICU LGPL-2.1 MIT MPL-2.0 Unicode-DFS-2016 Unlicense Zlib
Requires: tree-sitter-lib = %{version}-%{release}
Requires: tree-sitter-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# tree-sitter
[![DOI](https://zenodo.org/badge/14164618.svg)](https://zenodo.org/badge/latestdoi/14164618)
[![discord][discord]](https://discord.gg/w7nTvsVJhm)
[![matrix][matrix]](https://matrix.to/#/#tree-sitter-chat:matrix.org)

%package dev
Summary: dev components for the tree-sitter package.
Group: Development
Requires: tree-sitter-lib = %{version}-%{release}
Provides: tree-sitter-devel = %{version}-%{release}
Requires: tree-sitter = %{version}-%{release}

%description dev
dev components for the tree-sitter package.


%package lib
Summary: lib components for the tree-sitter package.
Group: Libraries
Requires: tree-sitter-license = %{version}-%{release}

%description lib
lib components for the tree-sitter package.


%package license
Summary: license components for the tree-sitter package.
Group: Default

%description license
license components for the tree-sitter package.


%prep
%setup -q -n tree-sitter-0.23.0
cd %{_builddir}
tar xf %{_sourcedir}/tree-sitter-2024-08-26-17-00-12.tar.xz
cd %{_builddir}/tree-sitter-0.23.0
mkdir -p ./vendor
cp -r %{_builddir}/tree-sitter-2024-08-26-17-00-12/* %{_builddir}/tree-sitter-0.23.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml
pushd ..
cp -a tree-sitter-0.23.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724855633
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  PREFIX=/usr LIBDIR=/usr/lib64

pushd ../buildavx2
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
make  %{?_smp_mflags}  PREFIX=/usr LIBDIR=/usr/lib64
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1724855633
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tree-sitter
cp %{_builddir}/tree-sitter-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/d5f7a0af7c0a54f099c103473760335c8d3341c2 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ahash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ahash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/2646b6d2453275031022ab245a3a6d5da4ba80b2 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle-wincon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle-wincon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/33dbd2d99ad231460bbb01812a52c85e577bd9ba || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/arbitrary/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/arbitrary/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/b12c210e78112e40e89cc0e765a6335c6b4636b2 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ascii/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/b2707f0f034cc936597a69b9657b04e5c5cbe225 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ascii/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/f30b44535cec0515071a712b0470674522616128 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/bindgen/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/8690c5c1d27c8829def121744e5bcd86f48788ef || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/bumpalo/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/bumpalo/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/0a1e89ac22450cb0311baa2613bc21b7131b321f || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/byteorder/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/bytes/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/2510927d07430a2092720e8f4a5287043f75e8d3 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cexpr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cexpr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/cd821ffa80099abbc31c22fe770022f3349e0918 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cfg_aliases/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/39806df76979277073594a0c19005c3c7fb17221 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/chunked_transfer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/chunked_transfer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/2aa704f32bad18e49ac5177a9d6e5e6e50372fc7 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clang-sys/LICENSE.txt %{buildroot}/usr/share/package-licenses/tree-sitter/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cobs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/combine/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/a2fe414fa386797e1732d5ad23bab9e6cfa7447b || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/core-foundation-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/core-foundation-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/core-foundation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/core-foundation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-bforest/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-codegen-meta/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-codegen-shared/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-codegen/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-control/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-entity/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-frontend/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-native/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/cranelift-wasm/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/crc32fast/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/crc32fast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/8f178d4cc55689ebdd562cabb1282e33bf8f32fe || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ctor/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/92a74693f02c8e78dd90b2014c52bc35a95bab86 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ctor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3a7a80be859f41edcaf9989291d2f4b04231d186 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ctrlc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/8bec88444202e13c35f17f3057132e6a21c287c1 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ctrlc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/diff/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/diff/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/0db0557c9a1561fa3aa6693747121458bf7ddfcd || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/dirs-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/43a3a49bd7af636c923a5ae475395b8e29320529 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/dirs-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/cf762fa3609793d5639ba9e1cbd254db276f50d3 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/dirs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/43a3a49bd7af636c923a5ae475395b8e29320529 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/dirs/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/cf762fa3609793d5639ba9e1cbd254db276f50d3 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/embedded-io-0.4.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/embedded-io/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/equivalent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/equivalent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/c371f0a7cbb203643d88566665a452f96bf1ab86 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/fallible-iterator/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/fallible-iterator/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4679f9ac0b7f5da9fd22e62c69771ff9331a7a3d || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/filetime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/filetime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/form_urlencoded/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/form_urlencoded/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/738188f5fed28a950b0fede659706238ec35f8bb || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/fs4/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/fs4/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/gimli/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/gimli/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/git2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/git2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/glob/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/glob/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/hashbrown-0.13.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/hashbrown-0.13.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/heck-0.4.1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/heck-0.4.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/home/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/1d47c63586fe3be7f228cff1ab0c029b53741875 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/home/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/html-escape/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/cc3825c3de7e0c8c644a6ed418cb748fd784cfa6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/httpdate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/1726596c1cc6c65d3a272abc337b13936430cf96 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/httpdate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/f516ded20090880b5bb281ad2f9dde3d94e9e369 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/id-arena/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/id-arena/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/idna/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/idna/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/is_terminal_polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/is_terminal_polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/jni-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/jni-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/e9863e11a6ae28d862197e5fbe364c290b9c1a62 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/jni/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/jni/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/e1618f901b8b4ea54621de7a573824fbfc1f2b13 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/jobserver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/jobserver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/js-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/js-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/lazycell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/lazycell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/bce2ed71de8bb33db2d29a5fcadd7407824e9248 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/leb128/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/leb128/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/libgit2/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/edbe3a1a51b534904dd0539218d7303a0deb28b0 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/libgit2/deps/http-parser/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/1a00a507fb89bb0018c092d6835077d541e76dc2 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/libgit2/deps/pcre/LICENCE %{buildroot}/usr/share/package-licenses/tree-sitter/936db4f914d8b9a516ac93a3bf7856c8bfeb6855 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/libgit2/deps/pcre/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/tree-sitter/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/libgit2/deps/winhttp/COPYING.GPL %{buildroot}/usr/share/package-licenses/tree-sitter/302250717721b22e804054f10e5a8d9c6e7328c4 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/libgit2/deps/winhttp/COPYING.LGPL %{buildroot}/usr/share/package-licenses/tree-sitter/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libgit2-sys/libgit2/deps/zlib/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/07821586dcc816d67ff045b9708fe8291fd67e62 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libloading/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/4ad37fc99fecc5cda018043361f5b12e350e4052 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libm/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libm/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/744183c4ca46703f4b738aca20e238e11c9a3b12 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libredox/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f5a7ee42dcefea5415e6af50baca4e0c338bd8fe || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libz-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libz-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/76c0e372bfabc4a503dd04d9281f808b33ded4f0 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libz-sys/src/zlib-ng/LICENSE.md %{buildroot}/usr/share/package-licenses/tree-sitter/1e0b08e7a2124c67c42261ac819e2340a2dd912c || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libz-sys/src/zlib/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/233f44af3fb55dcc7fddfef8e77ac627b0008756 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/libz-sys/src/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/tree-sitter/892b34f7865d90a6f949f50d95e49625a10bc7f0 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/mach2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/mach2/LICENSE-BSD %{buildroot}/usr/share/package-licenses/tree-sitter/24b715e62cdfc7753030f43432f6dd229d136c25 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/mach2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/21ecd644e03f61f0d9f8ee3bcc5c207435ff60ca || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/memchr/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/memfd/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/memfd/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/43b8d6c1a1b26fd324975a5125e85ed98408b5ab || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/minimal-lexical/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/minimal-lexical/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/minimal-lexical/LICENSE.md %{buildroot}/usr/share/package-licenses/tree-sitter/cd3fe820606ed34ac2591caf068c7cabd3ab3509 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/nix/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/nom/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/27ea6989d4f34b7b944eb884410a31ae20d11686 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/object/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/object/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/dd2f4bd6d87fe2780fc8e4135ce7dac6ff0b33ee || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/openssl-probe/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/openssl-probe/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/openssl-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/option-ext/LICENSE.txt %{buildroot}/usr/share/package-licenses/tree-sitter/8fcc05c0dd9d9c76e948120c9520e4cbe85fb527 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/paste/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/paste/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/percent-encoding/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/percent-encoding/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/pin-project-lite/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/pin-project-lite/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/pretty_assertions/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/pretty_assertions/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4c1c71430c0885114ef42fc256b803241cdcf898 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/prettyplease/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/prettyplease/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/psm/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/b14178d9219feaced7e8b313f9def76386c51ce7 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/psm/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/484cc3dce0ffeb128e73bde74b02603e66d7f13c || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/tree-sitter/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/tree-sitter/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/tree-sitter/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/redox_users/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/c56bd0668edca4d06b6cd881d4d2839da53058cd || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regalloc2/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/tree-sitter/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rustc-hash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rustc-hash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/tree-sitter/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/same-file/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/semver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/semver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde_spanned/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/serde_spanned/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/shlex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/a97a2888bca904918b3b9ec008fde1d6e9905a6d || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/shlex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/64e8197cb5ae680fcf996cc0ac8760e9f1e2e3a6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/similar/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/slice-group-by/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/078f087adf77f5f069ce72c0d56326b143beb438 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/smallbitvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/smallbitvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/1b1d8d3776317b7dfea5c7ad946ed727d16a89fa || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/stable_deref_trait/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/stable_deref_trait/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/f81793ddf50f460d6111fcbc799cab1a804aa000 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/strsim/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/termcolor/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/termcolor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/termcolor/UNLICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tiny_http/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tiny_http/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/06ec49f2eaa274e4270977b8ecc06d01cc4ae821 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tinyvec/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/tree-sitter/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tinyvec/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/tree-sitter/a9f37c2baefe44e0ddb6ee2809a101b2b9ef3935 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tinyvec/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/tree-sitter/9a00b14a56488f555c9ddecdc261e1b4daffb5b8 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tinyvec_macros/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/tree-sitter/8cc042e8e4b82c5532c72172a1988a74a599d4b5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tinyvec_macros/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/tree-sitter/86d193cb6b24df990cbbaf67c6a24fddbcb574c1 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/toml/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/toml/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/toml_datetime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/toml_datetime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/toml_edit/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/toml_edit/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tracing-attributes/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tracing-core/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tracing-core/src/spin/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/0956f8ac49e23a546fb113f711d7cdc0c3e98c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/tracing/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-bidi/COPYRIGHT %{buildroot}/usr/share/package-licenses/tree-sitter/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-bidi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-bidi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/tree-sitter/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-normalization/COPYRIGHT %{buildroot}/usr/share/package-licenses/tree-sitter/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-normalization/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-normalization/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-xid/COPYRIGHT %{buildroot}/usr/share/package-licenses/tree-sitter/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-xid/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unicode-xid/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/url/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/url/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/utf8-width/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/cc3825c3de7e0c8c644a6ed418cb748fd784cfa6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/vcpkg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/f85f58f2b17e35a1c2fd852cd58e5bae165ebea9 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/vcpkg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3ede8a2ceb97cd197183b1a9d7958b57cea01e14 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/walkdir/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-macro-support/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-macro-support/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-shared/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen-shared/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasm-bindgen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasmtime-cranelift/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasmtime-environ/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasmtime-types/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/wasmtime/LICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/web-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/web-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/webbrowser/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/8f8395cf4e2fd34f2bb875b8e8589dd3dd5d5062 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/webbrowser/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/87cf8ffaf0a2e8427f8cd3e65334bc538aadd9c2 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/which/LICENSE.txt %{buildroot}/usr/share/package-licenses/tree-sitter/a8ced9a6c206a0e47fac6c6d0d0ce839e85b2eb7 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys-0.45.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys-0.45.0/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys-0.48.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys-0.48.0/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys-0.52.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys-0.52.0/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-targets-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-targets-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-targets-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-targets-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_gnullvm-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_gnullvm-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_msvc-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_msvc-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnu-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnu-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_msvc-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_msvc-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnu-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnu-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnullvm-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnullvm-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_msvc-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_msvc-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/winnow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/yansi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/yansi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/2508ba1b598baf9b1b094b1092ff88a8fae154e7 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy-derive/LICENSE-BSD %{buildroot}/usr/share/package-licenses/tree-sitter/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy/LICENSE-BSD %{buildroot}/usr/share/package-licenses/tree-sitter/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy/src/third_party/rust/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tree-sitter-2024-08-26-17-00-12/zerocopy/src/third_party/rust/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3 PREFIX=/usr LIBDIR=/usr/lib64
popd
GOAMD64=v2
%make_install PREFIX=/usr LIBDIR=/usr/lib64
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/tree_sitter/api.h
/usr/lib64/libtree-sitter.so
/usr/lib64/pkgconfig/tree-sitter.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libtree-sitter.so.0.23
/usr/lib64/libtree-sitter.so.0
/usr/lib64/libtree-sitter.so.0.23

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tree-sitter/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/tree-sitter/06ec49f2eaa274e4270977b8ecc06d01cc4ae821
/usr/share/package-licenses/tree-sitter/07821586dcc816d67ff045b9708fe8291fd67e62
/usr/share/package-licenses/tree-sitter/078f087adf77f5f069ce72c0d56326b143beb438
/usr/share/package-licenses/tree-sitter/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/tree-sitter/0956f8ac49e23a546fb113f711d7cdc0c3e98c85
/usr/share/package-licenses/tree-sitter/0a1e89ac22450cb0311baa2613bc21b7131b321f
/usr/share/package-licenses/tree-sitter/0db0557c9a1561fa3aa6693747121458bf7ddfcd
/usr/share/package-licenses/tree-sitter/1726596c1cc6c65d3a272abc337b13936430cf96
/usr/share/package-licenses/tree-sitter/1a00a507fb89bb0018c092d6835077d541e76dc2
/usr/share/package-licenses/tree-sitter/1b1d8d3776317b7dfea5c7ad946ed727d16a89fa
/usr/share/package-licenses/tree-sitter/1d47c63586fe3be7f228cff1ab0c029b53741875
/usr/share/package-licenses/tree-sitter/1e0b08e7a2124c67c42261ac819e2340a2dd912c
/usr/share/package-licenses/tree-sitter/21ecd644e03f61f0d9f8ee3bcc5c207435ff60ca
/usr/share/package-licenses/tree-sitter/233f44af3fb55dcc7fddfef8e77ac627b0008756
/usr/share/package-licenses/tree-sitter/24b715e62cdfc7753030f43432f6dd229d136c25
/usr/share/package-licenses/tree-sitter/2508ba1b598baf9b1b094b1092ff88a8fae154e7
/usr/share/package-licenses/tree-sitter/2510927d07430a2092720e8f4a5287043f75e8d3
/usr/share/package-licenses/tree-sitter/2646b6d2453275031022ab245a3a6d5da4ba80b2
/usr/share/package-licenses/tree-sitter/27ea6989d4f34b7b944eb884410a31ae20d11686
/usr/share/package-licenses/tree-sitter/2aa704f32bad18e49ac5177a9d6e5e6e50372fc7
/usr/share/package-licenses/tree-sitter/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/tree-sitter/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/tree-sitter/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/tree-sitter/302250717721b22e804054f10e5a8d9c6e7328c4
/usr/share/package-licenses/tree-sitter/33dbd2d99ad231460bbb01812a52c85e577bd9ba
/usr/share/package-licenses/tree-sitter/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/tree-sitter/39806df76979277073594a0c19005c3c7fb17221
/usr/share/package-licenses/tree-sitter/3a7a80be859f41edcaf9989291d2f4b04231d186
/usr/share/package-licenses/tree-sitter/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/tree-sitter/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/tree-sitter/3c8e7847ca19c2bb00f4100c725810c04a1b56d6
/usr/share/package-licenses/tree-sitter/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/tree-sitter/3ede8a2ceb97cd197183b1a9d7958b57cea01e14
/usr/share/package-licenses/tree-sitter/43a3a49bd7af636c923a5ae475395b8e29320529
/usr/share/package-licenses/tree-sitter/43b8d6c1a1b26fd324975a5125e85ed98408b5ab
/usr/share/package-licenses/tree-sitter/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/tree-sitter/4679f9ac0b7f5da9fd22e62c69771ff9331a7a3d
/usr/share/package-licenses/tree-sitter/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1
/usr/share/package-licenses/tree-sitter/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/tree-sitter/484cc3dce0ffeb128e73bde74b02603e66d7f13c
/usr/share/package-licenses/tree-sitter/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c
/usr/share/package-licenses/tree-sitter/4ad37fc99fecc5cda018043361f5b12e350e4052
/usr/share/package-licenses/tree-sitter/4c1c71430c0885114ef42fc256b803241cdcf898
/usr/share/package-licenses/tree-sitter/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/tree-sitter/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/tree-sitter/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/tree-sitter/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/tree-sitter/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/tree-sitter/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/tree-sitter/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/tree-sitter/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/tree-sitter/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/tree-sitter/64e8197cb5ae680fcf996cc0ac8760e9f1e2e3a6
/usr/share/package-licenses/tree-sitter/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/tree-sitter/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/tree-sitter/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/tree-sitter/6c2945f449081ab19640fb7c70a081a1a4559399
/usr/share/package-licenses/tree-sitter/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/tree-sitter/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/tree-sitter/738188f5fed28a950b0fede659706238ec35f8bb
/usr/share/package-licenses/tree-sitter/744183c4ca46703f4b738aca20e238e11c9a3b12
/usr/share/package-licenses/tree-sitter/76c0e372bfabc4a503dd04d9281f808b33ded4f0
/usr/share/package-licenses/tree-sitter/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/tree-sitter/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/tree-sitter/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/tree-sitter/8690c5c1d27c8829def121744e5bcd86f48788ef
/usr/share/package-licenses/tree-sitter/86d193cb6b24df990cbbaf67c6a24fddbcb574c1
/usr/share/package-licenses/tree-sitter/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd
/usr/share/package-licenses/tree-sitter/87cf8ffaf0a2e8427f8cd3e65334bc538aadd9c2
/usr/share/package-licenses/tree-sitter/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/tree-sitter/8bec88444202e13c35f17f3057132e6a21c287c1
/usr/share/package-licenses/tree-sitter/8cc042e8e4b82c5532c72172a1988a74a599d4b5
/usr/share/package-licenses/tree-sitter/8f178d4cc55689ebdd562cabb1282e33bf8f32fe
/usr/share/package-licenses/tree-sitter/8f8395cf4e2fd34f2bb875b8e8589dd3dd5d5062
/usr/share/package-licenses/tree-sitter/8fcc05c0dd9d9c76e948120c9520e4cbe85fb527
/usr/share/package-licenses/tree-sitter/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/tree-sitter/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/tree-sitter/92a74693f02c8e78dd90b2014c52bc35a95bab86
/usr/share/package-licenses/tree-sitter/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/tree-sitter/936db4f914d8b9a516ac93a3bf7856c8bfeb6855
/usr/share/package-licenses/tree-sitter/9a00b14a56488f555c9ddecdc261e1b4daffb5b8
/usr/share/package-licenses/tree-sitter/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/tree-sitter/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/tree-sitter/a2fe414fa386797e1732d5ad23bab9e6cfa7447b
/usr/share/package-licenses/tree-sitter/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/tree-sitter/a6fe1503554eb18138838c526d150f58fc104133
/usr/share/package-licenses/tree-sitter/a81399b7c3ec2d4619848fd59c11d21211fc3b86
/usr/share/package-licenses/tree-sitter/a8ced9a6c206a0e47fac6c6d0d0ce839e85b2eb7
/usr/share/package-licenses/tree-sitter/a97a2888bca904918b3b9ec008fde1d6e9905a6d
/usr/share/package-licenses/tree-sitter/a9f37c2baefe44e0ddb6ee2809a101b2b9ef3935
/usr/share/package-licenses/tree-sitter/b12c210e78112e40e89cc0e765a6335c6b4636b2
/usr/share/package-licenses/tree-sitter/b14178d9219feaced7e8b313f9def76386c51ce7
/usr/share/package-licenses/tree-sitter/b2707f0f034cc936597a69b9657b04e5c5cbe225
/usr/share/package-licenses/tree-sitter/bce2ed71de8bb33db2d29a5fcadd7407824e9248
/usr/share/package-licenses/tree-sitter/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca
/usr/share/package-licenses/tree-sitter/c371f0a7cbb203643d88566665a452f96bf1ab86
/usr/share/package-licenses/tree-sitter/c56bd0668edca4d06b6cd881d4d2839da53058cd
/usr/share/package-licenses/tree-sitter/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/tree-sitter/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/tree-sitter/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/tree-sitter/cc3825c3de7e0c8c644a6ed418cb748fd784cfa6
/usr/share/package-licenses/tree-sitter/cd3fe820606ed34ac2591caf068c7cabd3ab3509
/usr/share/package-licenses/tree-sitter/cd821ffa80099abbc31c22fe770022f3349e0918
/usr/share/package-licenses/tree-sitter/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/tree-sitter/cf762fa3609793d5639ba9e1cbd254db276f50d3
/usr/share/package-licenses/tree-sitter/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/tree-sitter/d5f7a0af7c0a54f099c103473760335c8d3341c2
/usr/share/package-licenses/tree-sitter/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/tree-sitter/dd2f4bd6d87fe2780fc8e4135ce7dac6ff0b33ee
/usr/share/package-licenses/tree-sitter/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/tree-sitter/e1618f901b8b4ea54621de7a573824fbfc1f2b13
/usr/share/package-licenses/tree-sitter/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/tree-sitter/e9863e11a6ae28d862197e5fbe364c290b9c1a62
/usr/share/package-licenses/tree-sitter/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/tree-sitter/ebbc0758a0322f1bfe28f5438867a084e53941c8
/usr/share/package-licenses/tree-sitter/edbe3a1a51b534904dd0539218d7303a0deb28b0
/usr/share/package-licenses/tree-sitter/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/tree-sitter/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/tree-sitter/f30b44535cec0515071a712b0470674522616128
/usr/share/package-licenses/tree-sitter/f516ded20090880b5bb281ad2f9dde3d94e9e369
/usr/share/package-licenses/tree-sitter/f5a7ee42dcefea5415e6af50baca4e0c338bd8fe
/usr/share/package-licenses/tree-sitter/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/tree-sitter/f81793ddf50f460d6111fcbc799cab1a804aa000
/usr/share/package-licenses/tree-sitter/f85f58f2b17e35a1c2fd852cd58e5bae165ebea9
/usr/share/package-licenses/tree-sitter/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/tree-sitter/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/tree-sitter/ff3ed70db4739b3c6747c7f624fe2bad70802987
